version: '3.9'

services:

  app:
    build: .
    entrypoint: tail -F anything
    volumes:
      - .:/app

# # Test with:
# # (while running microfetch-pipeline web service on host port 8000)
# cd app
# NXF_ANSI_LOG=false nextflow run main.nf --output_dir /app/test_output --fastq_pattern "*{R,_}{1,2}.fastq.gz" --adapter_file /app/adapters.fas --qc_conditions /app/qc_conditions_nextera_relaxed.yml --full_output --cutadapt -profile test --api_url http://host.docker.internal:8000/api/ -stub-run